DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS VEHICLE_DETAILS;
DROP TABLE IF EXISTS VAHICLE_FEATURE;
DROP TABLE IF EXISTS VAHICLE_PRICE;

CREATE TABLE VEHICLE_DETAILS (
			DETAILS_ID INTEGER NOT NULL AUTO_INCREMENT,
			MAKE VARCHAR(100) NOT NULL,
			MODEL VARCHAR(100) NOT NULL,
			MODEL_YEAR INTEGER NOT NULL,
			BODY_STYLE VARCHAR(100) NOT NULL,
			ENGINE VARCHAR(100) NOT NULL,
			DRIVE_TYPE VARCHAR(100) NOT NULL,
			COLOR VARCHAR(100) NOT NULL,
			MPG INTEGER NOT NULL,
			PRIMARY KEY (DETAILS_ID));
			
CREATE TABLE VEHICLE_FEATURE (
			FEATURE_ID INTEGER NOT NULL AUTO_INCREMENT,
			EXTERIOR VARCHAR(100) NOT NULL,
			INTERIOR VARCHAR(100) NOT NULL,
			PRIMARY KEY (FEATURE_ID));
			
CREATE TABLE VEHICLE_PRICE (
			PRICE_ID INTEGER NOT NULL AUTO_INCREMENT,
			MSRP VARCHAR(100) NOT NULL,
			SAVINGS VARCHAR(100) NOT NULL,
			FINAL_PRICE VARCHAR(100) NOT NULL,
			PRIMARY KEY (PRICE_ID));
			
CREATE TABLE VEHICLE (
			VEHICLE_ID INTEGER NOT NULL AUTO_INCREMENT,
			DETAILS_ID INTEGER NOT NULL,
			FEATURE_ID INTEGER NOT NULL,
			PRICE_ID INTEGER NOT NULL,
			PRIMARY KEY (VEHICLE_ID),
			FOREIGN KEY (DETAILS_ID) REFERENCES VEHICLE_DETAILS(DETAILS_ID),
			FOREIGN KEY (FEATURE_ID) REFERENCES VEHICLE_FEATURE(FEATURE_ID),
			FOREIGN KEY (PRICE_ID) REFERENCES VEHICLE_PRICE(PRICE_ID));